version: "3"

services:
  device_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: JuYH6GwXLD
      MYSQL_DATABASE: device_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: JuYH6GwXLD
    ports:
      - "6606:3306"
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=ON
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
  device_auth_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    networks:
      - internal
    depends_on:
      - device_db
volumes:
  mysql-data:
    driver: local

networks:
    internal:
        driver: bridge

