# Generated by Django 4.1 on 2022-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_product_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
