# Generated by Django 4.1 on 2022-10-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_alter_attributevalue_attribue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
        migrations.CreateModel(
            name='GiftProductTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_target', to='borrow.gift')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_target', to='borrow.product')),
            ],
            options={
                'db_table': 'gift_product_target',
            },
        ),
        migrations.CreateModel(
            name='GiftProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift', to='borrow.gift')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='borrow.product')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sku', to='borrow.attributevalue')),
            ],
            options={
                'db_table': 'gift_product',
            },
        ),
    ]
