# Generated by Django 4.1 on 2022-11-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_gift_giftproducttarget_giftproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_a', to='borrow.product'),
        ),
    ]
