# Generated by Django 4.1 on 2022-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMAUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField(default=2)),
                ('user_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
